name: 2dgs_slam
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - wandb
  - open3d
  - opencv
  - trimesh
  - torchmetrics
  - rich
  - rerun-sdk
  - huggingface_hub
  - omegaconf
  - moviepy
  - addict
  - pip:
    - munch
    - evo