inherit_from: "configs/rgb/video/base_config.yaml"

Dataset:
  type: "video"
  dataset_path: "/home/sergio/2dgs_slam/demo_videos/iphone_flowers.mp4"
  frame_rate: 30  # Sample at 30 FPS (-1 for all frames)
  start_frame: 0  # Optional
  end_frame: -1   # Optional (-1 for last frame)
  resize_percent: 50.0  # Resize to 50% of original resolution (100.0 = no resize)
  
  Calibration:
    fx: 525.0
    fy: 525.0
    cx: 319.5
    cy: 239.5
    width: 640   # Original video width
    height: 480  # Original video height
    distorted: false
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0